LOCAL_SRC_FILES := \
	../../../UniversalRecognizer/V300/InkData/InkData.cpp \
	../../../UniversalRecognizer/V300/InkData/PHStream.cpp \
	../../../UniversalRecognizer/V300/InkData/PHStroke.cpp \
	../../../UniversalRecognizer/V300/InkData/UndoAction.cpp \
	../../../UniversalRecognizer/V300/InkData/InkWrapper.cpp \
	../../../UniversalRecognizer/V300/InkData/ShapesRec.cpp \
	../../../UniversalRecognizer/V300/InkData/ImageObject.cpp \
	../../../UniversalRecognizer/V300/InkData/TextObject.cpp \
	../../../UniversalRecognizer/V300/RecognizerWrapper/gestures.cpp \
	../../../UniversalRecognizer/V300/RecognizerWrapper/PhatCalc.cpp \
	../../../UniversalRecognizer/V300/RecognizerWrapper/WordFile.cpp \
	../../../UniversalRecognizer/V300/RecognizerWrapper/WordLrnFile.cpp \
	../../../UniversalRecognizer/V300/RecognizerWrapper/RecognizerWrapper.cpp \
	../../../UniversalRecognizer/V300/reco/src/reco.cpp \
	../../../UniversalRecognizer/V300/reco/src/recokern.cpp \
	../../../UniversalRecognizer/V300/reco/src/recolibs.cpp \
	../../../UniversalRecognizer/V300/reco/src/recoutil.cpp \
	../../../UniversalRecognizer/V300/reco/src/recodict.cpp \
	../../../UniversalRecognizer/V300/reco/src/hwrctype.cpp \
	../../../UniversalRecognizer/V300/reco/src/post_cap_tbl.cpp \
	../../../UniversalRecognizer/V300/reco/src/post_capital.cpp \
	../../../UniversalRecognizer/V300/reco/src/hwrswap.cpp \
	../../../UniversalRecognizer/V300/reco/src/langutil.cpp \
	../../../UniversalRecognizer/V300/reco/src/hwrmem.cpp \
	../../../UniversalRecognizer/V300/reco/src/hwrmath.cpp \
	../../../UniversalRecognizer/V300/reco/src/hwrstr.cpp \
	../../../UniversalRecognizer/V300/reco/src/letimagestodte.cpp \
	../../../UniversalRecognizer/V300/reco/src/dtiutil.cpp \
	../../../UniversalRecognizer/V300/reco/src/ldbutil.cpp \
	../../../UniversalRecognizer/V300/reco/src/ligstate.cpp \
	../../../UniversalRecognizer/V300/reco/src/newdict.cpp \
	../../../UniversalRecognizer/V300/reco/src/spell.cpp \
	../../../UniversalRecognizer/V300/reco/src/calccell.cpp \
	../../../UniversalRecognizer/V300/reco/src/bitmaps.cpp \
	../../../UniversalRecognizer/V300/reco/src/param.cpp \
	../../../UniversalRecognizer/V300/reco/src/angle.cpp \
	../../../UniversalRecognizer/V300/reco/src/arcs.cpp \
	../../../UniversalRecognizer/V300/reco/src/breaks.cpp \
	../../../UniversalRecognizer/V300/reco/src/check.cpp \
	../../../UniversalRecognizer/V300/reco/src/circle.cpp \
	../../../UniversalRecognizer/V300/reco/src/convert.cpp \
	../../../UniversalRecognizer/V300/reco/src/cross_geometry.cpp \
	../../../UniversalRecognizer/V300/reco/src/cross.cpp \
	../../../UniversalRecognizer/V300/reco/src/triadsutil.cpp \
	../../../UniversalRecognizer/V300/reco/src/connections.cpp \
	../../../UniversalRecognizer/V300/reco/data/dti_img.cpp \
	../../../UniversalRecognizer/V300/reco/data/ldb_img.cpp \
	../../../UniversalRecognizer/V300/reco/data/snn_img.cpp \
	../../../UniversalRecognizer/V300/reco/data/trd_img.cpp \
	../../../UniversalRecognizer/V300/reco/data/vprf_img.cpp \
	../../../UniversalRecognizer/V300/reco/data/vsuf_img.cpp \
	../../../UniversalRecognizer/V300/reco/src/xrdict.cpp \
	../../../UniversalRecognizer/V300/reco/src/utils.cpp \
	../../../UniversalRecognizer/V300/reco/src/xrattrib.cpp \
	../../../UniversalRecognizer/V300/reco/src/xrmatrix.cpp \
	../../../UniversalRecognizer/V300/reco/src/poly.cpp \
	../../../UniversalRecognizer/V300/reco/src/mlp.cpp \
	../../../UniversalRecognizer/V300/reco/src/filter.cpp \
	../../../UniversalRecognizer/V300/reco/src/pict.cpp \
	../../../UniversalRecognizer/V300/reco/src/prep.cpp \
	../../../UniversalRecognizer/V300/reco/src/sketch.cpp \
	../../../UniversalRecognizer/V300/reco/src/stroke.cpp \
	../../../UniversalRecognizer/V300/reco/src/stroke1.cpp \
	../../../UniversalRecognizer/V300/reco/src/links.cpp \
	../../../UniversalRecognizer/V300/reco/src/link_begin.cpp \
	../../../UniversalRecognizer/V300/reco/src/link_next.cpp \
	../../../UniversalRecognizer/V300/reco/src/low3.cpp \
	../../../UniversalRecognizer/V300/reco/src/low_util.cpp \
	../../../UniversalRecognizer/V300/reco/src/luspecl.cpp \
	../../../UniversalRecognizer/V300/reco/src/tracedata.cpp \
	../../../UniversalRecognizer/V300/reco/src/dct_functions.cpp \
	../../../UniversalRecognizer/V300/reco/src/low_data.cpp \
	../../../UniversalRecognizer/V300/reco/src/apostroph.cpp \
	../../../UniversalRecognizer/V300/reco/src/wordbreaks.cpp \
	../../../UniversalRecognizer/V300/reco/src/wordcorrector.cpp \
	../../../UniversalRecognizer/V300/reco/src/worddict.cpp \
	../../../UniversalRecognizer/V300/reco/src/wordsegment.cpp \
	../../../UniversalRecognizer/V300/reco/src/precutil.cpp
