/***************************************************************************************
 *
 *  WRITEPAD(r): Handwriting Recognition Engine (HWRE) and components.
 *  Copyright (c) 2001-2016 PhatWare (r) Corp. All rights reserved.
 *
 *  Licensing and other inquires: <developer@phatware.com>
 *  Developer: Stan Miasnikov, et al. (c) PhatWare Corp. <http://www.phatware.com>
 *
 *  WRITEPAD HWRE is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  THE MATERIAL EMBODIED ON THIS SOFTWARE IS PROVIDED TO YOU "AS-IS"
 *  AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE,
 *  INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR
 *  FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL PHATWARE CORP.
 *  BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT, SPECIAL, INCIDENTAL,
 *  INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER,
 *  INCLUDING WITHOUT LIMITATION, LOSS OF PROFIT, LOSS OF USE, SAVINGS
 *  OR REVENUE, OR THE CLAIMS OF THIRD PARTIES, WHETHER OR NOT PHATWARE CORP.
 *  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS, HOWEVER CAUSED AND ON
 *  ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE
 *  POSSESSION, USE OR PERFORMANCE OF THIS SOFTWARE.
 *  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with WritePad.  If not, see <http://www.gnu.org/licenses/>.
 *
 **************************************************************************************/

/* ************************************************************************************* */
/* *    PhatWare WritePad handwriting recognition engine                               * */
/* *    Copyright (c) 1997-2014 PhatWare(r) Corp. All rights reserved.                 * */
/* ************************************************************************************* */

/* ************************************************************************************* *
 *
 * File: Wordlist
 *
 * Unauthorized distribution of this code is prohibited.
 * Contractor/manufacturer is PhatWare Corp.
 * 1314 S. Grand Blvd. Ste. 2-175 Spokane, WA 99202
 *
 * ************************************************************************************* */

#pragma once

static const char * g_szDefWords_BRZ[] = {

	"adimiss\xe3o",		"admiss\xe3o",
	"adimitir",			"admitir",
	"adivogado",		"advogado",
	"aer",				"era",
	"aida",				"ainda",
	"algmu",			"algum",
	"ams",				"mas",
	"an",				"na",
	"analize",			"an\xe1lise",
	"angulo",			"\xe2ngulo",
	"apos",				"ap\xf3s",
	"apra",				"para",
	"aqeule",			"aquele",
	"aqiulo",			"aquilo",
	"arco\xedris",			"arco-\xedris",
	"ar\xe9",				"at\xe9",
	"asim",				"assim",
	"aspeto",			"aspecto",
	"assin",			"assim",
	"assougue",			"a\xe7ougue",
	"aue",				"que",
	"augum",			"algum",
	"augun",			"algum",
	"ben",				"bem",
	"beringela",		"berinjela",
	"bon",				"bom",
	"cafe",				"caf\xe9",
	"caichote",			"caixote",
	"capit\xf5\x65s",			"capit\xe3\x65s",
	"cidad\xe3\x65s",			"cidad\xe3os",
	"ckaro",			"claro",
	"cliche",			"clich\xea",
	"compreenss\xe3o",		"compreens\xe3o",
	"comprens\xe3o",		"compreens\xe3o",
	"comun",			"comum",
	"con",				"com",
	"contezto",			"contexto",
	"corrijir",			"corrigir",
	"coxixar",			"cochichar",
	"cpm",				"com",
	"cppara",			"para",
	"dai",				"da\xed",
	"danca",			"dan\xe7\x61",
	"decer",			"descer",	
	"definitamente",	"definitivamente",
	"deshonestidade",	"desonestidade",
	"deshonesto",		"desonesto",
	"detale",			"detalhe",
	"deven",			"devem",
	"distingeu",		"distingue",
	"dsa",				"das",
	"dze",				"dez",
	"d\xed\x66icil",			"dif\xed\x63il",
	"ecess\xe3o",			"exce\xe7\xe3o",
	"ecess\xf5\x65s",			"exce\xe7\xf5\x65s",
	"eent\xe3o",			"e ent\xe3o",
	"emb",				"bem",
	"ems",				"sem",
	"emu",				"meu",
	"en",				"em",
	"enbora",			"embora",
	"equ",				"que",
	"ero",				"erro",
	"erv",				"ver",
	"esata",			"exata",
	"ese",				"esse",
	"essel\xeancia",		"excel\xeancia",
	"esu",				"seu",
	"euq",				"que",
	"excess\xe3o",			"exce\xe7\xe3o",	
	"excess\xf5\x65s",		"exce\xe7\xf5\x65s",
	"excur\xe7\xe3o",			"excurs\xe3o",
	"exeplo",			"exemplo",
	"exijir",			"exigir",
	"exij\xeancia",		"exig\xeancia",
	"expont\xe2neo",		"espont\xe2neo",
	"ezata",			"exata",
	"ezemplo",			"exemplo",
	"ezerc\xed\x63io",		"exerc\xed\x63io",
	"ez\xe9rcito",			"ex\xe9rcito",
	"faciu",			"f\xe1\x63il",
	"fas",				"faz",
	"faser",			"fazer",
	"fente",			"gente",
	"ferias",			"f\xe9rias",
	"foce",				"fosse",
	"geito",			"jeito",
	"gib\xf3ia",			"jib\xf3ia",
	"gil\xf3",				"jil\xf3",
	"gipe",				"jipe",
	"guardi\xe3os",		"guardi\xf5\x65s",
	"ha",				"h\xe1",
	"hezitar",			"hesitar",
	"hezita\xe7\xe3o",		"hesita\xe7\xe3o",
	"interesado",		"interessado",
	"interese",			"interesse",
	"iso",				"isso",
	"isot",				"isto",
	"ja",				"j\xe1",
	"jente",			"gente",
	"larangeira",		"laranjeira",
	"linah",			"linha",
	"linguissa",		"ling\xfci\xe7\x61",
	"lingui\xe7\x61",			"ling\xfci\xe7\x61",
	"maizena",			"maisena",	
	"masi",				"mais",
	"maz",				"mas",
	"mbe",				"bem",
	"mco",				"com",
	"melior",			"melhor",
	"mema",				"mesma",
	"menas",			"menos",
	"mes",				"m\xeas",
	"miu",				"mil",
	"mque",				"quem",
	"msa",				"mas",
	"mte",				"tem",
	"mu",				"um",
	"mue",				"meu",
	"muinto",			"muito",
	"muitp",			"muito",
	"nao",				"n\xe3o",
	"nehum",			"nenhum",
	"nenhun",			"nenhum",
	"nenina",			"menina",
	"nenino",			"menino",
	"nesa",				"nessa",
	"nese",				"nesse",
	"nimho",			"ninho",
	"noso",				"nosso",
	"no\xe3",				"n\xe3o",
	"nso",				"nos",
	"oa",				"ao",
	"obiter",			"obter",
	"observacao",		"observa\xe7\xe3o",
	"obssecado",		"obcecado",
	"obsserva\xe7\xe3o",		"observa\xe7\xe3o",
	"ocm",				"com",
	"ons",				"nos",
	"opr",				"por",
	"orijem",			"origem",
	"orijen",			"origem",
	"ospital",			"hospital",
	"oter",				"obter",
	"otra",				"outra",
	"otro",				"outro",
	"oy",				"ou",
	"parachoque",		"p\xe1ra-choque",
	"pesquizar",		"pesquisar",
	"poden",			"podem",
	"popr\xf3sito",		"prop\xf3sito",
	"portugu6es",		"portugu\xeas",
	"porwue",			"porque",
	"potugu\xeas",			"portugu\xeas",
	"po\xe7uir",			"possuir",
	"precisan",			"precisam",
	"preten\xe7\xe3o",		"pretens\xe3o",
	"propio",			"pr\xf3prio",
	"propo",			"propor",
	"pr\xf3pio",			"pr\xf3prio",
	"ps",				"os",
	"qaundo",			"quando",
	"qeu",				"que",
	"qmue",				"quem",
	"qque",				"que",
	"quado",			"quando",
	"quasi",			"quase",
	"quiz",				"quis",
	"rae",				"era",
	"reciz\xe3o",			"rescis\xe3o",
	"rev",				"ver",
	"rpo",				"por",
	"rse",				"ser",
	"sa",				"as",
	"sanque",			"sangue",
	"sao",				"s\xe3o",
	"sau",				"sal",
	"sbo",				"sob",
	"sda",				"das",
	"sen",				"sem",
	"sensivel",			"sens\xedvel",
	"senssibilidade",	"sensibilidade",
	"senss\xedvel",		"sens\xedvel",
	"sequ\xe9ncia",		"seq\xfc\xeancia",	
	"sia",				"sai",
	"significatimente",	"significativamente",
	"sinceranete",		"sinceramente",
	"sov",				"sob",
	"sovre",			"sobre",
	"sre",				"ser",
	"srm",				"sem",
	"susseder",			"suceder",
	"sussess\xe3o",		"sucess\xe3o",
	"tanbem",			"tamb\xe9m",
	"tanb\xe9m",			"tamb\xe9m",
	"tda",				"toda",
	"tdo",				"todo",
	"ten",				"tem",
	"testo",			"texto",
	"tit\xfalo",			"t\xedtulo",
	"tre",				"ter",
	"tydo",				"tudo",
	"t\xe9xtil",			"t\xeaxtil",
	"ue",				"eu",
	"un",				"um",
	"una",				"uma",
	"unica",			"\xfanica",
	"unico",			"\xfanico",
	"utilisar",			"utilizar",
	"utilise",			"utilize",
	"utlizar",			"utilizar",
	"uzar",				"usar",
	"uzo",				"uso",
	"vega",				"veja",
	"ven",				"vem",
	"viage",			"viagem",
	"vja",				"veja",
	"voc6e",			"voc\xea",
	"voc\xe9",				"voc\xea",
	"wue",				"que",
	"xap\xe9u",			"chap\xe9u",
	"xave",				"chave",
	"zde",				"dez",
	"\xedtens",			"itens",	
};

#define DEFWORDCNT_BRZ  (sizeof(g_szDefWords_BRZ)/sizeof(g_szDefWords_BRZ[0]))


