/***************************************************************************************
 *
 *  WRITEPAD(r): Handwriting Recognition Engine (HWRE) and components.
 *  Copyright (c) 2001-2016 PhatWare (r) Corp. All rights reserved.
 *
 *  Licensing and other inquires: <developer@phatware.com>
 *  Developer: Stan Miasnikov, et al. (c) PhatWare Corp. <http://www.phatware.com>
 *
 *  WRITEPAD HWRE is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  THE MATERIAL EMBODIED ON THIS SOFTWARE IS PROVIDED TO YOU "AS-IS"
 *  AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE,
 *  INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR
 *  FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL PHATWARE CORP.
 *  BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT, SPECIAL, INCIDENTAL,
 *  INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER,
 *  INCLUDING WITHOUT LIMITATION, LOSS OF PROFIT, LOSS OF USE, SAVINGS
 *  OR REVENUE, OR THE CLAIMS OF THIRD PARTIES, WHETHER OR NOT PHATWARE CORP.
 *  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS, HOWEVER CAUSED AND ON
 *  ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE
 *  POSSESSION, USE OR PERFORMANCE OF THIS SOFTWARE.
 *  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with WritePad.  If not, see <http://www.gnu.org/licenses/>.
 *
 **************************************************************************************/

#pragma once

// Autocorrector list for US English recognizer

static const char * g_szDefWords_EUS[] = {
    "aboot",	       "about",
    "abouta",         "about a",
    "aboutit",        "about it",
    "abscence",       "absence",
    "accessories",    "accessories",
    "accidant",       "accident",
    "accomodate",     "accommodate",
    "accordingto",    "according to",
    "accross",        "across",
    "acheive",        "achieve",
    "acheived",       "achieved",
    "acheiving",      "achieving",
    "acommodate",     "accommodate",
    "acomodate",      "accommodate",
    "accomodate",     "accommodate",
    "additinal",      "additional",
    "addtional",      "additional",
    "adequit",        "adequate",
    "adequite",       "adequate",
    "advanage",       "advantage",
    "affraid",        "afraid",
    "aggresive",      "aggressive",
    "agreemeent",     "agreement",
    "agreemeents",    "agreements",
    "agreemnets",     "agreements",
    "agressive",      "aggressive",
    "alot",           "a lot",
    "alraedy",        "already",
    "alwats",         "always",
    "alway",          "always",
    "Ameria",         "America",
    "anual",          "annual",
    "apparant",       "apparent",
    "apparrent",      "apparent",
    "appearence",     "appearance",
    "appeares",       "appears",
    "applyed",        "applied",
    "approrpiate",    "appropriate",
    "approrpriate",   "appropriate",
    "aquisition",     "acquisition",
    "aquisitions",    "acquisitions",
    "are:t",          "aren't",
    "arent",          "aren't",
    "arguement",      "argument",
    "arguements",     "arguments",
    "are't",          "aren't",
    "aren:t",         "aren't",
    "arond",          "around",
    "artical",        "article",
    "articel",        "article",
    "assistent",      "assistant",
    "atention",       "attention",
    "atmospher",      "atmosphere",
    "audeince",       "audience",
    "audiance",       "audience",
    "availalbe",      "available",
    "balence",        "balance",
    "ballance",       "balance",
    "becaus",         "because",
    "becauseof",      "because of",
    "becomeing",      "becoming",
    "becomming",      "becoming",
    "becuz",          "because",
    "beggining",      "beginning",
    "begining",       "beginning",
    "beleiev",        "believe",
    "beleieve",       "believe",
    "beleif",         "belief",
    "beleive",        "believe",
    "beleived",       "believed",
    "beleives",       "believes",
    "benifit",        "benefit",
    "benifits",       "benefits",
    "betwen",         "between",
    "beutiful",       "beautiful",
    "blase",          "blas\xE9",
    "facade",         "fa\xE7\x61\x64\x65",
    "boxs",           "boxes",
    "brodcast",       "broadcast",
    "cafe",           "caf\xE9",
    "caharcter",      "character",
    "calcullated",    "calculated",
    "calulated",      "calculated",
    "can;t",          "can't",
    "candidta",       "candidate",
    "candidtaes",     "candidates",
    "cant",           "can't",
    "catagory",       "category",
    "categiory",      "category",
    "certian",        "certain",
    "challange",      "challenge",
    "challanges",     "challenges",
    "changable",      "changeable",
    "changeing",      "changing",
    "changng",        "changing",
    "charachter",     "character",
    "charachters",    "characters",
    "charactor",      "character",
    "charecter",      "character",
    "charector",      "character",
    "cheif",          "chief",
    "cieling",        "ceiling",
    "circut",         "circuit",
    "claer",          "clear",
    "claered",        "cleared",
    "claerly",        "clearly",
    "cliant",         "client",
    "cliche",         "clich\xE9",
    "colection",      "collection",
    "comapnies",      "companies",
    "combintation",   "combination",
    "comited",        "committed",
    "comittee",       "committee",
    "comming",        "coming",
    "commitee",       "committee",
    "committe",       "committee",
    "committment",    "commitment",
    "committments",   "commitments",
    "committy",       "committee",
    "compair",        "compare",
    "company;s",      "company's",
    "compleated",     "completed",
    "compleatly",     "completely",
    "compleatness",   "completeness",
    "completly",      "completely",
    "completness",    "completeness",
    "composate",      "composite",
    "comtain",        "contain",
    "comtains",       "contains",
    "comunicate",     "communicate",
    "comunity",       "community",
    "condolances",    "condolences",
    "conected",       "connected",
    "conferance",     "conference",
    "confirmmation",  "confirmation",
    "considerit",     "considerate",
    "considerite",    "considerate",
    "consonent",      "consonant",
    "conspiricy",     "conspiracy",
    "consultent",     "consultant",
    "convertable",    "convertible",
    "cooparate",      "cooperate",
    "cooporate",      "cooperate",
    "corproation",    "corporation",
    "corproations",   "corporations",
    "corruptable",    "corruptible",
    "cotten",         "cotton",
    "coudn't",        "couldn't",
    "couldn;t",       "couldn't",
    "couldnt",        "couldn't",
    "creme",          "cr\xE8me",
    "ctaegory",       "category",
    "cusotmer",       "customer",
    "cusotmers",      "customers",
    "danceing",       "dancing",
    "dcument",        "document",
    "deatils",        "details",
    "decison",        "decision",
    "decisons",       "decisions",
    "decor",          "d\xE9\x63or",
    "defendent",      "defendant",
    "definately",     "definitely",
    "deptartment",    "department",
    "desicion",       "decision",
    "desicions",      "decisions",
    "desision",       "decision",
    "desisions",      "decisions",
    "detente",        "d\xE9tente",
    "develeoprs",     "developers",
    "devellop",       "develop",
    "develloped",     "developed",
    "develloper",     "developer",
    "devellopers",    "developers",
    "develloping",    "developing",
    "devellopment",   "development",
    "devellopments",  "developments",
    "devellops",      "develop",
    "develope",       "develop",
    "developement",   "development",
    "developements",  "developments",
    "developor",      "developer",
    "developors",     "developers",
    "develpment",     "development",
    "diaplay",        "display",
    "didint",         "didn't",
    "did;t",          "didn't",
    "didnot",         "did not",
    "didnt",          "didn't",
    "difefrent",      "different",
    "diferences",     "differences",
    "differance",     "difference",
    "differances",    "differences",
    "differant",      "different",
    "differemt",      "different",
    "differnt",       "different",
    "diffrent",       "different",
    "directer",       "director",
    "directers",      "directors",
    "directiosn",     "direction",
    "disatisfied",    "dissatisfied",
    "discoverd",      "discovered",
    "disign",         "design",
    "dispaly",        "display",
    "dissonent",      "dissonant",
    "distribusion",   "distribution",
    "divsion",        "division",
    "don;t",          "don't",
    "docuemnt",       "document",
    "documetn",       "document",
    "documnet",       "document",
    "documnets",      "documents",
    "doese",          "does",
    "doesn;t",        "doesn't",
    "doesnt",         "doesn't",
    "doign",          "doing",
    "doimg",          "doing",
    "doind",          "doing",
    "dollers",        "dollars",
	"dejavu",		  "d\xE9j\xE0 vu",
	"deja",			  "d\xE9j\xE0",
    "don;t",          "don't",
    "dont",           "don't",
    "driveing",       "driving",
    "eclair",         "\xE9\x63lair",
    "effecient",      "efficient",
    "efort",          "effort",
    "eforts",         "efforts",
    "eligable",       "eligible",
    "embarass",       "embarrass",
    "emigre",         "\xE9migr\xE9",
    "e-mail",         "email",
    "entree",         "entr\xE9\x65",
    "equippment",     "equipment",
    "equivalant",     "equivalent",
    "especally",      "especially",
    "espesially",     "especially",
    "excellant",      "excellent",
    "excercise",      "exercise",
    "excitment",      "excitement",
    "exhcange",       "exchange",
    "exhcanges",      "exchanges",
    "experiance",     "experience",
    "exprienced",     "experienced",
    "faeture",        "feature",
    "faetures",       "features",
    "familair",       "familiar",
    "familar",        "familiar",
    "familliar",      "familiar",
    "fammiliar",      "familiar",
    "feild",          "field",
    "feilds",         "fields",
    "fianlly",        "finally",
    "firends",        "friends",
    "firts",          "first",
    "fora",           "for a",
    "foriegn",        "foreign",
    "forwrd",         "forward",
    "forwrds",        "forwards",
    "foudn",          "found",
    "foward",         "forward",
    "fowards",        "forwards",
    "freind",         "friend",
    "freinds",        "friends",
    "furneral",       "funeral",
    "garantee",       "guarantee",
    "gemeral",        "general",
    "gerat",          "great",
    "geting",         "getting",
    "gettin",         "getting",
    "gievn",          "given",
    "giveing",        "giving",
    "govenment",      "government",
    "goverment",      "government",
    "guidlines",      "guidelines",
    "hadbeen",        "had been",
    "hadn:t",         "hadn't",
    "hadnt",          "hadn't",
    "haev",           "have",
    "hapen",          "happen",
    "hapened",        "happened",
    "hapening",       "happening",
    "hapens",         "happens",
    "happend",        "happened",
    "hasbeen",        "has been",
    "hasn;t",         "hasn't",
    "hasnt",          "hasn't",
    "havebeen",       "have been",
    "haveing",        "having",
    "haven;t",        "haven't",
    "havent",         "haven't",
    "hel",            "he'll",
    "helpfull",       "helpful",
    "heres",          "here's",
    "hes",            "he's",
    "hesaid",         "he said",
    "hewas",          "he was",
    "hismelf",        "himself",
    "hvaing",         "having",
	"Htp",			  "http",
	"Http",			  "http",
	"http:\\\\",	  "http://",
	"http:11",		  "http://",
    "i;d",            "I'd",
    "i;ll",           "I'll",
	"l'll",			  "I'll",
	"l'm",			  "I'm",
	"1'm",			  "I'm",
	"1m",			  "I'm",
    ";s",             "is",
    ";sa",            "is a",
    "identofy",       "identify",
    "il",             "I'll",
    "im",             "I'm",
    "imediate",       "immediate",
    "imediatly",      "immediately",
    "immediatly",     "immediately",
    "importent",      "important",
    "importnat",      "important",
    "impossable",     "impossible",
    "improvemnt",     "improvement",
    "improvment",     "improvement",
    "indecate",       "indicate",
    "indenpendence",  "independence",
    "indenpendent",   "independent",
    "indepedent",     "independent",
    "independance",   "independence",
    "independant",    "independent",
    "influance",      "influence",
    "infomation",     "information",
    "informatoin",    "information",
    "inital",         "initial",
    "insted",         "instead",
    "insurence",      "insurance",
    "interum",        "interim",
    "inthe",          "in the",
    "inwhich",        "in which",
    "isnt",           "isn't",
    "isthe",          "is the",
    "itis",           "it is",
    "ititial",        "initial",
    "itll",           "it'll",
    "it:ll",          "it'll",
	"it;ll",          "it'll",
    "itnerest",       "interest",
    "itnerested",     "interested",
    "itneresting",    "interesting",
    "itnerests",      "interests",
	"ipad"			  "iPad",
	"ipod"			  "iPod",
	"iphone",		  "iPhone",
    "isa",            "is a",
    "itsa",           "it's a",
    "itwas",          "it was",
    "ive",            "I've",
	"i;ve",           "I've",
    "i:ve",           "I've",
    "jugment",        "judgment",
    "judgement",      "judgment",
    "knowldge",       "knowledge",
    "knowlege",       "knowledge",
    "kwarters",       "quarters",
    "labratory",      "laboratory",
    "lastyear",       "last year",
    "learnign",       "learning",
    "lenght",         "length",
    "let:s",          "let's",
	"let;s",          "let's",
    "libary",         "library",
    "librarry",       "library",
    "librery",        "library",
    "lieutenent",     "lieutenant",
    "likly",          "likely",
    "lisense",        "license",
    "liveing",        "living",
    "lonly",          "lonely",
    "maintenence",    "maintenance",    
    "managment",      "management",
    "mantain",        "maintain",
    "marraige",       "marriage",
    "merchent",       "merchant",
    "mesage",         "message",
    "mesages",        "messages",
    "mispell",        "misspell",
    "mispelling",     "misspelling",
    "mispellings",    "misspellings",
    "morgage",        "mortgage",
    "mysefl",         "myself",
    "naive",          "na\xEFve",
    "necassarily",    "necessarily",
    "necassary",      "necessary",
    "neccessarily",   "necessarily",
    "neccessary",     "necessary",
    "necesarily",     "necessarily",
    "necesary",       "necessary",
    "negotiaing",     "negotiating",
    "noone",          "no one",
    "nothign",        "nothing",
    "nver",           "never",
    "obediant",       "obedient",
    "ocasion",        "occasion",
    "occassion",      "occasion",
    "occured",        "occurred",
    "occurence",      "occurrence",
    "occurrance",     "occurrence",
    "oclock",         "o'clock",
    "ocur",           "occur",
    "ofits",          "of its",
    "ofthe",          "of the",
    "oneof",          "one of",
    "onepoint",       "one point",
    "onthe",          "on the",
    "oppasite",       "opposite",
    "opperation",     "operation",
    "oppertunity",    "opportunity",
    "opposate",       "opposite",
    "opposible",      "opposable",
    "opposit",        "opposite",
    "oppotunities",   "opportunities",
    "oppotunity",     "opportunity",
    "orginization",   "organization",
    "orginized",      "organized",
    "outof",          "out of",
    "overthe",        "over the",
    "oxident",        "oxidant",
    "parliment",      "parliament",
    "partof",         "part of",
    "peice",          "piece",
    "peices",         "pieces",
    "percentof",      "percent of",
    "percentto",      "percent to",
    "performence",    "performance",
    "perhasp",        "perhaps",
    "perhpas",        "perhaps",
    "permanant",      "permanent",
    "perminent",      "permanent",
    "pleasent",       "pleasant",
    "porblems",       "problems",
    "porvide",        "provide",
    "potentialy",     "potentially",
    "pregnent",       "pregnant",
    "presance",       "presence",
    "prominant",      "prominent",
    "protege",        "prot\xE9g\xE9",
    "protoge",        "prot\xE9g\xE9",
    "psoition",       "position",
    "ptogress",       "progress",
    "puting",         "putting",
    "quater",         "quarter",
    "quesion",        "question",
    "quesions",       "questions",
    "reccomend",      "recommend",
    "reccommend",     "recommend",
    "receieve",       "receive",
    "recieve",        "receive",
    "recieved",       "received",
    "recieving",      "receiving",
    "recomend",       "recommend",
    "recomendation",  "recommendation",
    "recomendations", "recommendations",
    "recomended",     "recommended",
    "reconize",       "recognize",
    "recrod",         "record",
    "religous",       "religious",
    "reluctent",      "reluctant",
    "representativs", "representatives",
    "representives",  "representatives",
    "resollution",    "resolution",
    "resorces",       "resources",
    "respomd",        "respond",
    "respomse",       "response",
    "responce",       "response",
    "responsability", "responsibility",
    "responsable",    "responsible",
    "responsibile",   "responsible",
    "responsiblity",  "responsibility",
    "restaraunt",     "restaurant",
    "restuarant",     "restaurant",
    "reveiw",         "review",
    "reveiwing",      "reviewing",
    "rote",           "wrote",
    "rumers",         "rumors",
    "rythm",          "rhythm",
    "rithm",          "rhythm",
    "rhithm",         "rhythm",
    "scedule",        "schedule",
    "sceduled",       "scheduled",
    "seance",         "s\xE9\x61nce",
    "secratary",      "secretary",
    "sectino",        "section",
    "selectoin",      "selection",
    "sentance",       "sentence",
    "seperate",       "separate",
    "sercumstances",  "circumstances",
    "skool",          "school",
    "shel",           "she'll",
    "shineing",       "shining",
    "shiped",         "shipped",
    "shouldent",      "shouldn't",
    "shouldnt",       "shouldn't",
    "signifacnt",     "significant",
    "simalar",        "similar",
    "similiar",       "similar",
    "sincerly",       "sincerely",
    "someting",       "something",
    "somthing",       "something",
    "somtimes",       "sometimes",
    "speach",         "speech",
    "specificaly",    "specifically",
    "statment",       "statement",
    "statments",      "statements",
    "strentgh",       "strength",
    "struggel",       "struggle",
    "strugle",        "struggle",
    "studnet",        "student",
    "successfull",    "successful",
    "successfuly",    "successfully",
    "sucess",         "success",
    "sucessfull",     "successful",
    "sufficiant",     "sufficient",
    "suposed",        "supposed",
    "suppossed",      "supposed",
    "suprise",        "surprise",
    "suprised",       "surprised",
    "swiming",        "swimming",
    "tecnical",       "technical",
    "teh",            "the",
    "termoil",        "turmoil",
    "thats",          "that's",
    "thatthe",        "that the",
    "themself",       "themselves",
    "themselfs",      "themselves",
    "thenew",         "the new",
    "thesame",        "the same",
    "thetwo",         "the two",
    "theyd",          "they'd",
    "theyll",         "they'll",
    "theyre",         "they're",
    "theyve",         "they've",
    "thier",          "their",
    "thisyear",       "this year",
    "threatend",      "threatened",
    "tne",            "the",
    "tbe",            "the",
    "togehter",       "together",
    "tomorow",        "tomorrow",
    "totaly",         "totally",
    "tothe",          "to the",
    "transfered",     "transferred",
    "truely",         "truly",
    "truley",         "truly",
    "tryed",          "tried",
    "udnerstand",     "understand",
    "understnad",     "understand",
    "unitedstates",   "United States",
    "unpleasently",   "unpleasantly",
    "untill",         "until",
    "useing",         "using",
    "visavis",        "vis-\xE0-vis",
    "vulnerible",     "vulnerable",
    "warrent",        "warrant",
    "wasnt",          "wasn't",
    "wel",            "we'll",
    "werent",         "weren't",
    "wern't",         "weren't",
    "what:s",         "what's",
    "whats",          "what's",
    "wheres",         "where's",
    "wherre",         "where",
	"who:s",          "who's",
	"who:ve",         "who've",
	"who;s",          "who's",
	"who;ve",         "who've",
    "wholl",          "who'll",
    "whos",           "who's",
    "whove",          "who've",
    "wierd",          "weird",
    "willbe",         "will be",
    "windoes",        "windows",
    "witha",          "with a",
    "wo'nt",          "won't",
    "wont",           "won't",
    "wouldnt",        "wouldn't",
    "writting",       "writing",
    "wroet",          "wrote",
    "wuould",         "would",
    "yera",           "year",
    "yeras",          "years",
    "yersa",          "years",
    "yoiu",           "you",
	"yov",			   "you",
    "youare",         "you are",
    "youd",           "you'd",
    "youll",          "you'll",
    "youre",          "you're",
    "youve",          "you've",
    "you;d",          "you'd",
    "you;ll",         "you'll",
    "you;re",         "you're",
    "you;ve",         "you've",
	"you:d",          "you'd",
	"you:ll",         "you'll",
	"you:re",         "you're",
	"you:ve",         "you've",
};

#define DEFWORDCNT_EUS  (sizeof(g_szDefWords_EUS)/sizeof(g_szDefWords_EUS[0]))

