/***************************************************************************************
 *
 *  WRITEPAD(r): Handwriting Recognition Engine (HWRE) and components.
 *  Copyright (c) 2001-2016 PhatWare (r) Corp. All rights reserved.
 *
 *  Licensing and other inquires: <developer@phatware.com>
 *  Developer: Stan Miasnikov, et al. (c) PhatWare Corp. <http://www.phatware.com>
 *
 *  WRITEPAD HWRE is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  THE MATERIAL EMBODIED ON THIS SOFTWARE IS PROVIDED TO YOU "AS-IS"
 *  AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE,
 *  INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR
 *  FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL PHATWARE CORP.
 *  BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT, SPECIAL, INCIDENTAL,
 *  INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER,
 *  INCLUDING WITHOUT LIMITATION, LOSS OF PROFIT, LOSS OF USE, SAVINGS
 *  OR REVENUE, OR THE CLAIMS OF THIRD PARTIES, WHETHER OR NOT PHATWARE CORP.
 *  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS, HOWEVER CAUSED AND ON
 *  ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE
 *  POSSESSION, USE OR PERFORMANCE OF THIS SOFTWARE.
 *  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with WritePad.  If not, see <http://www.gnu.org/licenses/>.
 *
 **************************************************************************************/

#pragma once


// Autocorrector list for Danish recognizer

static const char *  g_szDefWords_DAN[] = {
	"Jy",					"Jeg",
	"Fi",					"Vi",
	"Sig",					"Jeg",
	"Jag",					"Jeg",
	"1alle",				"Alle",
	"Voves",				"Vores",
	"voves",				"vores",
	"jag",					"jeg",
	"jy",					"jeg",
	"hav",					"har",
	"J\xe6g",					"Jeg",
	"m\xe5neders",			"m\xe5neder",
	"Impoter",				"Importer",
	"opsaatning",			"ops\xe6tning",
	"gofr",				"g\xf8r",
	"fsor",				"for",
	"sygdomne",			"sygdomme",
	"teak",				"tak",
	"fov",					"f\xf8r",
	"arg",					"\xe6g",
	"afgo\xf8re",				"afg\xf8re",
	"lolverand\xf8r",			"leverand\xf8r",
	"leverandefr",			"leverand\xf8r",
	"Eksporten",			"Eksporter",
	"inder",				"inden",
	"ynden",				"inden",
	"t|d",					"tid",
	"omelet",				"andet",
	"bak",					"tak",
	"forh\xe5ne",			"forh\xe5nd",
	"sidstourte",			"sidstn\xe6vnte",
	"jy",					"jeg",
	"jg",					"jeg",
	"sv\xe6re",				"v\xe6re",
	"svor",				"svar",
	"elle",				"eller",
	"Som",					"som",
	"sfationaser",			"station\xe6r",
	"compute",				"computer",
	"Vidager",				"Vi tager",
	"kaw",					"kan",
	"kam",					"kan",
	"kar",					"kan",
	"raelfe",				"v\xe6lge",
	"raelge",				"v\xe6lge",
	"saisom",				"saison",
	"graden",				"grader",
	"poi",					"p\xe5",
	"mauge",				"mange",
	"nnamse",				"mange",
	"daflige",				"daglige",
	"Skaldet",				"Skal det",
	"ligegade",			"liggende",
	"fofr",				"f\xf8r",
	"em",					"en",
	"ed",					"et",
	"Besudler",			"Desuden",
	"Derudevin",			"Derudover",
	"esuden",				"Desuden",
	"disto",				"desto",
	"es",					"Et",
	"Tirsctag",			"tirsdag",
	"Tirsdag",				"tirsdag",
	"Krouft",				"Kr\xe6\x66t",
	"Krouff",				"Kr\xe6\x66t",
	"hors",				"hvis",
	"sseyrste",			"st\xf8rste",
	"oforige",				"\xf8vrige",
	"Noj",					"Hej",
	"Nei",					"Nej",
	"foskning",			"forskning",
	"f9fdse",				"f\xf8\x64se",
	"fxsde",				"f\xf8\x64se",
	"goldse",				"f\xf8\x64se",
	"ua",					"af",
	"medarbirr",			"medarbejder",
	"bypisk",				"typisk",
	"pk",					"ok",
	"roj`se",				"rejse",
	"rejen",				"rejsen",
	"sf\xe8ve",				"sjove",
	"sfos-ve",				"sjove",
	"udeudefrs",			"udend\xf8rs",
	"kravenes",			"kr\xe6ver",
	"kraver",				"kr\xe6ver",
	"kr\xe6v",				"krav",
	"systemkr\xe6v",			"systemkrav",
	"ecksternt",			"eksternt",
	"eckstern",			"ekstern",
	"safter",				"s\xe6tter",
	"trault",				"travlt",
	"arbeidsmilj\xf8",		"arbejdsmilj\xf8",
	"\xc6rlig",				"\xe6rlig",
	"hoj",					"h\xf8j",
	"hoon\xe5r",				"hvorn\xe5r",
	"folgesedde",			"f\xf8lgesedde",
	"fosllgesedde",		"f\xf8lgesedde",
	"direktofr",			"direkt\xf8r",
	"modrselkab",			"moderselskab",
	"modrselskab",			"moderselskab",
	"f\xe6ridig",				"f\xe6rdig",
	"yeg",					"Jeg",
	"oin",					"\xe5r",
	"anet",				"andet",
	"Nar",					"N\xe5r",
	"gei",					"g\xe5",
	"Ebben",				"\xe5\x62\x65n",
	"ebben",				"\xe5\x62\x65n",
	"imis",				"UMTS",
	"urts",				"UMTS",
	"utits",				"UMTS",
	"m\xe5udelig",			"m\xe5ndelig",
	"oilig",				"\xe5rlig",
	"A0",					"\xc5",
	"l\xf8se",				"l\xf8ser",
	"l0sr",				"l\xf8ser",
	"l\xf8sningsforslaf",		"l\xf8sningsforslag",
	"leysnirf",			"l\xf8sning",
	"l0snrig",				"l\xf8sning",
	"gxr",					"g\xf8r",
	"ipad"			  "iPad",
	"ipod"			  "iPod",
	"iphone",		  "iPhone",
	"gxv",					"g\xf8r",
	"gofm",				"g\xf8r",
	"gofir",				"g\xf8r",
	"tsps",				"ApS",
	"tops",				"ApS",
	"g.ofre",				"g\xf8re",
	"goyne",				"g\xf8re",
	"gcxr",				"g\xf8r",
	"stols",				"stolt",
	"ruaegttab",			"v\xe6gttab",
	"s9/ndag",				"s\xf8ndag",
	"kongligktslof",		"konfliktstof",
	"kon5likstofs",		"konfliktstof",
	"konflikgtof",			"konfliktstof",
	"luderen",				"lederen",
	"gmforskre",			"genforskere",
	"Genforske",			"Genforsker",
	"bagi",				"bag",
	"stopps",				"stopper",
	"traw",				"kr\xe6ver",
	"narret",				"v\xe6rret",
	"Sygdomsgri",			"sygdomsfri",
	"sygdomsgri",			"sygdomsfri",
	"behanlirg",			"behandling",
	"behanling",			"behandling",
	"Gbbe",				"Ebbe",
	"esse",				"Ebbe",
	"S0r",					"f\xf8r",
	"lynet",				"l\xf8\x62\x65t",
	"brysthr\xe6\x66t",			"brystkr\xe6\x66t",
	"bwirkninger",			"bivirkninger",
	"e/delagte",			"\xf8\x64\x65lagte",
	"fos",					"Jeg",
	"Jrg",					"Jeg",
	"Jos",					"Jeg",
	"rofget",				"r\xf8get",
	"Ligestillingers",		"Ligestillingen",
	"h\xe5rdf",				"h\xe5rdt",
	"pr85",				"pres",
	"purg",				"pres",
	"nys",					"nyt",
	"lfxlge",				"if\xf8lge",
	"Situationer",			"Situationen",
	"R\xe5\x64husfladsen",		"R\xe5\x64huspladsen",
	"R^oidhuspladsen",		"R\xe5\x64huspladsen",
	"Smefrunr",			"Sm\xf8rum",
	"Sm9frum",				"Sm\xf8rum",
	"forellen",			"t\xe6ller",
	"foreller",			"t\xe6ller",
	"geigadea",			"g\xe5gaden",
	"geigaden",			"g\xe5gaden",
	"g^agadeu",			"g\xe5gaden",
	"Dygade",				"Bygade",
	"overashende",			"overraskende",
	"kon",					"Kom",
	"Wonla",				"World",
	"rronld",				"World",
	"Zsorld",				"World",
	"mord",				"Word",
	"Nykolbingi",			"Nyk\xf8\x62ing",
	"fluoren",				"bevarer",
	"forsoorets",			"forsvarets",
	"Duer",				"over",
	"orev",				"over",
	"Uirdrulle",			"virtuelle",
	"iirtuelle",			"virtuelle",
	"f6jemme",				"Hjemme",
	"hev",					"her",
	"fremmov",				"fremmer",
	"b\xf8vsende",			"b\xf8rnene",
	"menov",				"mener",
	"nar",					"n\xe5r",
	"if",					"\xc5",
	"^fb",					"\xc5",
	"t6",					"\xc5",
	"`a",					"\xe5",
	"kra8g",				"kraft",
	"uhlassificeret",		"uklassificeret",
	"persosnoplysningr",	"personoplysninger",
	"persoupplysninfer",	"personoplysninger",
	"(c)",					"\xa9",
	"(r)",					"\xae",
	"abbonement",			"abonnement",
	"abo",					"abonnement",
	"abbonnement",			"abonnement",
	"addresse",			"adresse",
	"adgagn",				"adgang",
	"adlrig",				"aldrig",
	"akceptere",			"acceptere",
	"aldrigt",				"aldrig",
	"alerede",				"allerede",
	"aligeve",			"alligeve",
	"allene",				"alene",
	"alrdig",				"aldrig",
	"als\xe5",				"alts\xe5",
	"annulere",			"annullere",
	"anullere",			"annullere",
	"apropo",				"apropos",
	"arangement",			"arrangement",
	"asistance",			"assistance",
	"debatere",			"debattere",
	"dene",				"denne",
	"detaille",			"detalje",
	"dete",				"dette",
	"diaglo",				"dialog",
	"diciplin",			"disciplin",
	"differance",			"difference",
	"dise",				"disse",
	"d:sse",				"disse",
	"exempe",				"eksempe",
	"f.ex.",				"f.eks.",
	"familje",				"familie",
	"financie",			"finansie",
	"financiere",			"finansiere",
	"forh\xe5\x62\x65nlig",			"forh\xe5\x62\x65ntlig",
	"forl\xe6ngst",			"for l\xe6ngst",
	"formandsskab",		"formandskab",
	"formenlig",			"formentlig",
	"forresten",			"for resten",
	"f\xf8lgeligt",			"f\xf8lgelig",
	"f\xe5\x65s",				"f\xe5s",
	"genenm",				"gennem",
	"gjordt",				"gjort",
	"grundliggende",		"grundl\xe6ggende",
	"halvtres",			"halvtreds",
	"heldigvist",			"heldigvis",
	"henholdsvist",		"henholdsvis",
	"hianden",				"hinanden",
	"hieraki",				"hierarki",
	"hinadnen",			"hinanden",
	"hirarki",				"hierarki",
	"hislen",				"hilsen",
	"hivs",				"hvis",
	"ifo/lge",				"if\xf8lge",
	"ialt",				"i alt",
	"indholder",			"indeholder",
	"indstallere",			"installlere",
	"indstallation",		"installation",
	"inflydelse",			"indflydelse",
	"inhold",				"indhold",
	"institutet",			"instituttet",
	"interresse",			"interesse",
	"irelevant",			"irrelevant",
	"klasifikation",		"klassifikation",
	"konferance",			"konference",
	"konkurent",			"konkurrent",
	"kontrolere",			"kontrollere",
	"medlemsskab",			"medlemskab",
	"nemligt",				"nemlig",
	"nummerisk",			"numerisk",
	"opn\xe5\x65s",				"opn\xe5s",
	"hoornar",				"hvorn\xe5r",
	"hoom^or",				"hvorfor",
	"Shalvi",				"Skal vi",
	"Skalbi",				"Skal vi",
	"has",					"har",
	"Has",					"Har",
	"hor",					"har",
	"l6oorfior",			"Hvorfor",
	"l6oorfos",			"Hvorfor",
	"T-lere",				"Flere",
	"klarg\xf8rings",			"klarg\xf8ring",
	"ar",					"\xe5r",
	"advorse",			"advarse",
	"sj\xe6ldend",			"sj\xe6ldende",
	"isvorfos",			"Hvorfor",
	"Leg",					"Jeg",
	"Horfor",				"Hvorfor",
	"Hon\xe5r",				"Hvorn\xe5r",
	"Salvi",				"Skal vi",
	"ui",					"vi",
	"wi",					"vi",
	"bu",					"du",
	"wig",					"mig",
	"uig",					"mig",
	"Slalvi",				"Skal vi",
	"Huem",				"Hvem",
	"otrolig",				"utrolig",
	"vtrolig",				"utrolig",
	"vedhaftet",			"vedh\xe6\x66tet",
	"arstid",				"\xe5rstid",
	"flu",					"fly",
	"flubilleter",			"flybilletter",
	"tug",					"tog",
	"ogso",				"ogs\xe5",
	"geukendelse",			"genkendelse",
	"geukend",				"genkend",
	"spandende",			"sp\xe6ndende",
	"p0",					"p\xe5",
	"beligsalg",			"boligsalg",
	"belig",				"bolig",
	"forhamdler",			"forhandler",
	"degne",				"tegne",
	"hudplyi",				"hudpleje",
	"l\xe6sr",				"l\xe6ser",
	"l\xe6sc",				"l\xe6se",
	"lnergi",				"energi",
	"lnergiplan",			"energiplan",
	"forhomder",			"forhandler",
	"andringer",			"\xe6ndringer",
	"Moursk",				"M\xe6rsk",
	"horwe",				"h\xe6ve",
	"harve",				"h\xe6ve",
	"tryb",				"tryk",
	"miljo",				"milj\xf8",
	"fa",					"f\xe5",
	"akasse",				"a-kasse",
	"v:de",				"vide",
	"j\xe9",					"jo",
	"lou",					"lov",
	"graviditeter",		"graviditeten",

};

#define DEFWORDCNT_DAN  (sizeof(g_szDefWords_DAN)/sizeof(g_szDefWords_DAN[0]))


