/*
 *  OptionKeys.h
 *  WritePad
 *
 *  Created by Stanislav Miasnikov on 11/8/08.
 *  Copyright 2008 PhatWare Corp.. All rights reserved.
 *
 */

#pragma once

// from WritePadViewController.m
#define kGeneralOptionsFirstStartKey		@"GeneralOptionsFirstStartKey"
#define kGenegalOptionsText					@"GenegalOptionsText"
#define kGenegalOptionsTextScrollPos		@"GenegalOptionsTextScrollPos"
#define kGenegalOptionsTextSelStart			@"GenegalOptionsTextSelStart"
#define kGenegalOptionsTextSelLength		@"GenegalOptionsTextSelLength"
#define kGenegalOptionsTextEditOn			@"GenegalOptionsTextEditOn"
#define kGenegalOptionsRecoMode				@"GenegalOptionsRecoMode"
#define kGeneralOptionsDisableRotation		@"GeneralOptionsDisableRotation"
#define kGeneralOptionsFileEncoding			@"GeneralOptionsFileEncoding"
#define kGeneralOptionsFileName				@"GeneralOptionsFileName"
#define kGeneralOptionsFolderName			@"GeneralOptionsFolderName"
#define kGeneralOptionsShowAllFolders		@"GeneralOptionsShowAllFolders"
#define kGeneralOptionsCurrentLanguage		@"GeneralOptionsCurrentLanguage"

#define kWritePadTintColor					@"WritePadTintColor"

// from WritePadEdit.h
#define kEditOptionsShowSuggestions			@"ShowSuggestionWindow"
#define kEditEnableSpellChecker				@"EditEnableSpellChecker"
#define kEditEnableTextAnalyzer				@"EditEnableTextAnalyzer"
#define kEditSetSelectMode					@"EditSetSelectMode"
#define kEditOptionsFontSize				@"EditFontSize"
#define kEditOptionsAutoColor               @"EditAutoColor"
#define kEditOptionsFontFace				@"EditFontFace"
#define kEditOptionsAutocapitalize			@"EditOptionsAutocapitalize"
#define kEditShowScrollButtons				@"EditShowScrollButtons"
#define kEditHideToolbar					@"EditHideToolbar"
#define kEditSearchMatchCase				@"EditSearchMatchCase"
#define kEditSearchWholeWord                @"EditSearchWholeWord"
#define kEditTextColor						@"EditTextColor"
#define kEditPageColor						@"EditPageColor"
#define kEditInkColor						@"EditInkColor"
#define kEditOptionsAlignment				@"EditOptionsAlignment"
#define kEditOptionsCustomStyles			@"EditOptionsCustomStyles"
#define kOptionsDocumentSortOrder			@"OptionsDocumentSortOrder"
#define kEditShowDocumentEnd                @"EditShowDocumentEnd"
#define kEditInkColorIndex                  @"EditInkColorIndex"
#define kInkcollectorWriteHere              @"InkcollectorWriteHere"
#define kEditOptionsDefaultFontFace         @"EditOptionsDefaultFontFace"
#define kEditOptionsDefaultFontSize         @"EditOptionsDefaultFontSize"
#define kSyncServiceiCloud                  @"SyncServiceiCloud"
#define kWritePadProSettings_ShowFormatbar  @"WritePadProSettings_ShowFormatbar"
#define kPrintDocumentHeader                @"kPrintDocumentHeader"
#define kPrintDocumentFooter                @"kPrintDocumentFooter"
#define kThemeBackImageIndex                @"ThemeBackImageIndex"

#define kSketchLineCapStyle                 @"SketchLineCapStyle"
#define kSketchLineWidth                    @"SketchLineWidth"
#define kSketchLineColor                    @"SketchLineColor"
#define kSketchBackgroundColor              @"SketchBackgroundColor"
#define kWritePadSynchronizationFolder      @"WritePadSynchronizationFolder"

#define kGeneralOptionsSearchHandwriting    @"GeneralOptionsSearchHandwriting"
#define kGeneralOptionsInputMode			@"GeneralOptionsInputMode"
#define kGeneralOptionsCurrentPageSize      @"GeneralOptionsCurrentPageSize"
#define kGeneralOptionsCurrentPageSizeHeight @"GeneralOptionsCurrentPageSizeHeight"
#define kGeneralOptionsCurrentPageSizeWidth @"GeneralOptionsCurrentPageSizeWidth"

// from InkCollectorView.h
#define kRecoOptionsAsyncRecoEnabled		@"EnableAsyncRecognizer"
#define kRecoOptionsInkWidth				@"RecoInkWidth"
#define kRecoOptionsSeparateLetters			@"RecoSeparateLettersMode"
#define kRecoOptionsSingleWordOnly			@"RecoDisableSegmentation"
#define kRecoOptionsInternational			@"RecoInternationalCharset"
#define kRecoOptionsDictOnly				@"RecoDictionaryOnly"
#define kRecoOptionsSuggestDictOnly			@"RecoDictionaryOnlySuggest"
#define kRecoOptionsUseUserDict				@"RecoEnableUserDict"
#define kRecoOptionsAddSpace				@"RecoOptionsAddSpace"
#define kRecoOptionsAddSpaceSingleLetter	@"RecoOptionsAddSpaceSingleLetter"
#define kRecoOptionsUseDynamicSegment       @"RecoOptionsUseDynamicSegment"

#define kRecoOptionsUseLearner				@"RecoUseLearner"
#define kRecoOptionsAsyncInking				@"EnableAsyncInkCollectpor"
#define kRecoOptionsTimerDelay				@"RecoTimerDelay"
#define kRecoOptionsTimerDelaySymbol		@"RecoTimerDelaySymbol"
#define kRecoOptionsSymbolRate              @"RecoOptionsSymbolRate"
#define kRecoOptionsBackstrokeLen			@"RecoBackstrokeLen"
#define kRecoOptionsInkColor				@"RecoInkColor"
#define kRecoOptionsDrawGrid				@"RecoDrawGrid"
#define kRecoOptionsUseCorrector			@"RecoUseCorrector"
#define kRecoOptionsErrorVibrate			@"RecoErrorVibrate"
#define kRecoOptionsErrorSound				@"RecoErrorSound"
#define kRecoOptionsSpellIgnoreNum			@"RecoOptionsSpellIgnoreNum"
#define kRecoOptionsSpellIgnoreUpper		@"RecoOptionsSpellIgnoreUpper"
#define kRecoOptionsInsertResult			@"RecoOptionsInsertResult"
#define kRecoOptionsLetterShapes			@"RecoOptionsLetterShapes"
#define kRecoOptionsAutoInsertResult        @"RecoOptionsAutoInsertResult"
#define kRecoOptionsSystemShorthands        @"RecoOptionsSystemShorthands"
#define kRecoOptionsSystemGestures          @"RecoOptionsSystemGestures"
#define RecoOptionsSettingsID               @"RecoOptionsSettings_ID424"
#define kRecoOptionsSmartPunctuationSpace   @"RecoOptionsSmartPunctuationSpace"
#define kRecoAllowLetterRecognizer          @"RecoAllowLetterRecognizer"

#define kUniqueApplicationID				@"UniqueApplicationID"

#define kGeneralOptionsGroupEvents			@"GeneralOptionsGroupEvents"
#define kGeneralOptionsGroupNotes			@"GeneralOptionsGroupNotes"
#define kGeneralOptionsGroupVoiceNotes		@"GeneralOptionsGroupVoiceNotes"
#define kGeneralOptionsGroupTasks			@"GeneralOptionsGroupTasks"
#define kGeneralOptionsGroupFolders			@"GeneralOptionsGroupFolders"
#define kGeneralOptionsTaskColors			@"GeneralOptionsTaskColors"
#define kGeneralOptionsEventColors			@"GeneralOptionsEventColors"
#define kGeneralOptionsNoteColors			@"GeneralOptionsNoteColors"
#define kGeneralOptionsNotePrivate			@"GeneralOptionsNotePrivate"
#define kGeneralOptionsNoteSubjectOnly		@"GeneralOptionsNoteSubjectOnly"
#define kGeneralOptionsVoiceNoteColors		@"GeneralOptionsVoiceNoteColors"
#define kGeneralOptionsNotePropBtn			@"GeneralOptionsNotePropBtn"
#define kGeneralOptionsShowSubject			@"GeneralOptionsShowSubject"

#define kGeneralOptionsLocationKey			@"GeneralOptionsLocationKey"
#define kGeneralOptionsShowSearch			@"GeneralOptionsShowSearch"
#define kGeneralOptionsSearchText			@"GeneralOptionsSearchText"
#define kGeneralOptionsLocalCopyPaste		@"GeneralOptionsLocalCopyPaste"
#define kGeneralOptionsReplaceText          @"GeneralOptionsReplaceText"

#define kTasksOptionsExportFile				@"TasksOptionsExportFile"

#define kGeneralOptionsShowCompleted		@"GeneralOptionsShowCompleted"
#define kGeneralOptionsShowPrivateTasks		@"GeneralOptionsShowPrivateTasks"
#define kGeneralOptionsShowPrivateNotes		@"GeneralOptionsShowPrivateNotes"
#define kGeneralOptionsShowPrivateEvents	@"GeneralOptionsShowPrivateEvents"
#define kGeneralOptionsShowPrivateVoice		@"GeneralOptionsShowPrivateVoice"
#define kGeneralOptionsHideCompleteBox		@"GeneralOptionsHideCompleteBox"
#define kGeneralOptionsShowCancelled		@"GeneralOptionsShowCancelled"
#define kGeneralOptionsDefaultIcon			@"GeneralOptionsDefaultIcon"
#define kGeneralOptionsShowPastDueBadge		@"GeneralOptionsShowPastDueBadge"

#define kJournalOptionsExportFile			@"JournalOptionsExportFile"
#define kGeneralOptionsShowMiscFields		@"GeneralOptionsShowMiscFields"
#define kGeneralOptionsCreateDefaultItems	@"GeneralOptionsCreateDefaultItems"

#define kGeneralOptionsEnableFileShare		@"GeneralOptionsEnableFileShare"
#define kGeneralOptionsEnableDataSync		@"GeneralOptionsEnableDataSync"
#define kGeneralOptionsHttpStayAwake		@"GeneralOptionsHttpStayAwake"
#define kGeneralOptionsEnableFilePassword	@"GeneralOptionsEnableFilePassword"
#define kGeneralOptionsHttpPassword			@"GeneralOptionsHttpPassword"
#define kGeneralOptionsUseKeyboard			@"GeneralOptionsUseKeyboard"

#define kRemoteNotificationsID				@"RemoteNotificationsID"
#define kRemoteNotificationsTMZ				@"RemoteNotificationsTMZ"

#define kOptionsFilterByPriority			@"OptionsFilterByPriority"
#define kOptionsFilterByDate				@"OptionsFilterByDate"
#define kOptionsFilterByText				@"OptionsFilterByDate"
#define kOptionsFilterByColor				@"OptionsFilterByColor"

#define kGeneralOptionsDefaultEmailTO		@"GeneralOptionsDefaultEmailTO"
#define kGeneralOptionsDefaultEmailCC		@"GeneralOptionsDefaultEmailCC"
#define kGeneralOptionsDefaultEmailBCC		@"GeneralOptionsDefaultEmailBCC"
#define kGeneralOptionsDefaultNoteColor		@"GeneralOptionsDefaultNoteColor"
#define kGeneralOptionsDefaultFolderColor	@"GeneralOptionsDefaultFolderColor"
#define kGeneralOptionsDefaultNoteCategoty	@"GeneralOptionsDefaultNoteCategoty"
#define kGeneralOptionsDefaultNotePriority	@"GeneralOptionsDefaultNotePriority"
#define kGeneralOptionsShowGroupsView		@"GeneralOptionsShowGroupsView"
#define kGeneralOptionsFileFormat			@"GeneralOptionsFileFormat"
#define kPhatPadOptionsGridSnap             @"PhatPadOptionsGridSnap"

#define kGeneralOptionsUseFilterCatrgory	@"GeneralOptionsFilterCatrgory"
#define kGeneralOptionsUseFilterColor		@"GeneralOptionsFilterColor"
#define kGeneralOptionsUseFilterPriority	@"GeneralOptionsFilterPriority"
#define kGeneralOptionsDefaultEmailSign		@"GeneralOptionsDefaultEmailSign"
#define kGeneralOptionsInitDefaults			@"GeneralOptionsInitDefaults_ID800"

#define kOptionsShareUserData				@"OptionsShareUserData"

#define kTranslatorCreateNew				@"TranslatorCreateNew"
#define kGeneralOptionsDefaultNoteIcon		@"GeneralOptionsDefaultNoteIcon"
#define kGeneralOptionsDefaultFolderIcon	@"GeneralOptionsDefaultFolderIcon"

#define EDITCTL_RELOAD_OPTIONS				(@"EDITCTL_RELOAD_OPTIONS")
	
#define kDropboxLastSyncDate				@"DropboxLastSyncDate"
#define kDropboxAutosyncStart				@"DropboxAutosyncStart"
#define kSyncServiceEnabled                 @"SyncServiceEnabled"

#define kPhatPadOptionsEnableShapes			@"PhatPadOptionsEnableShapes"
#define kPhatPadOptionsDeleteRecStrokes		@"PhatPadOptionsDeleteRecStrokes"
#define kPhatPadOptionsInkWidth				@"PhatPadOptionsInkWidth"
#define kPhatPadOptionsInkColor				@"PhatPadOptionsInkColor"
#define kPhatPadOptionsDrawGridV			@"PhatPadOptionsDrawGridV"
#define kPhatPadOptionsDrawGridH			@"PhatPadOptionsDrawGridH"
#define kPhatPadOptionsSpaceGridV           @"PhatPadOptionsSpaceGridV"
#define kPhatPadOptionsSpaceGridH           @"PhatPadOptionsSpaceGridH"
#define kPhatPadOptionsIgnoreShortStrokes	@"PhatPadOptionsIgnoreShortStrokes"
#define kPhatPadOptionsAdvancedInking		@"PhatPadOptionsAdvancedInking"
#define kPhatPadOptionsCustomPens			@"PhatPadOptionsCustomPens"
#define kPhatPadOptionsEnableEraseGesture	@"PhatPadOptionsEnableEraseGesture"
#define kPhatPadOptionsInputMode			@"PhatPadOptionsInputMode"
#define kPhatPadShowPagesView               @"PhatPadShowPagesView"

#define kPhatPadSwipeEnabled			    @"PhatPadSwipeEnabled"
#define kPhatPadPageColor					@"PhatPadPageColor"
#define kPresentationSoundEnabled			@"PresentationSoundEnabled"

// Evernote
#define kSyncConflictResolution				@"SyncConflictResolution"
#define kEvernoteDefaultNotebook			@"EvernoteDefaultNotebook"
#define kGeneralOptionsDontShowMsg1         @"GeneralOptionsDontShowMsg_ID700"
#define kGeneralOptionsDontShowWizard       @"GeneralOptionsDontShowWizard_ID700"
#define kWritePadSyncPlaySound              @"WritePadSyncPlaySound"

#define kTextFontStyleView                  @"TextFontStyleView"
#define kTextSearchStyleView                @"TextSearchStyleView"
#define kTouchAndHoldTimeout                @"TouchAndHoldTimeout"

#define kCenterStylusPosition               @"CenterStylusPosition"
#define kCenterStylusPressure               @"CenterStylusPressure"
#define kCenterStylusPalmRest               @"CenterStylusPalmRest"
#define kCenterStylusPalmRestWarning        @"CenterStylusPalmRestWarning"
#define kCenterStylusCmdButton1             @"CenterStylusCmdButton1"
#define kCenterStylusCmdButton2             @"CenterStylusCmdButton2"
#define kCenterStylusCmdFeedback            @"CenterStylusCmdFeedback"
#define kCenterStylusEnable                 @"CenterStylusEnable"
#define kCenterStylusBambooPalmRest         @"CenterStylusBambooPalmRest"

#define kVoiceSpeakWhileWriting             @"VoiceSpeakWhileWriting"
#define kVoiceSpeakingSpeed                 @"VoiceSpeakingSpeed"
#define kVoiceSpeakingPitch                 @"VoiceSpeakingPitch"
#define kVoiceSpeakingVolume                @"VoiceSpeakingVolume"
#define kVoiceSpeakingVoice                 @"VoiceSpeakingVoice"

#define kColorPaletteLoadFixedColors        @"ColorPaletteLoadFixedColors"
#define kWritePanelStyle                    @"WritePanelStyle"
#define kInputPanelMarkerPosition           @"InputPanelMarkerPosition"
#define kInputPanelWriteHere                @"InputPanelWriteHere"
#define kTextEditDateFomratID               @"TextEditDateFomratID"
#define kTextEditCustomDateFomratString     @"TextEditCustomDateFomratString"

#define kEvernoteLastSyncDate               @"EvernoteLastSyncDate"
#define kBoxLastSyncDate                    @"BoxLastSyncDate"
#define kDropboxLastSyncDate                @"DropboxLastSyncDate"
#define kOneDriveLastSyncDate               @"OneDriveLastSyncDate"
#define kGoogleDriveLastSyncDate            @"GoogleDriveLastSyncDate"

#define kPhatCloudSynchronizationFolder     @"PhatCloudSynchronizationFolder"
#define kPhatCloudSortIndex                 @"PhatCloudSortIndex"
#define kRecoKeyboardCustomKey              @"RecoKeyboardCustomKey"

#define kWritePadPersistentDataDate         @"WritePadPersistentDataDate"
#define kShowStartupWizard                  @"ShowStartupWizard_ID700"
#define kWritePadLastUsedFiles              @"WritePadLastUsedFiles"

#define kGeneralOptionsInitSync             @"GeneralOptionsInitSync_ID700"
#define kSharedStoreNeedsReloadFileList     @"SharedStoreReloadFileList"
#define kSharedStoreChangedFileName         @"SharedStoreChangedFileName"
#define kSharedStoreDeletedFileName         @"SharedStoreDeletedFileName"

#define kEditOptionsDisableLoup             @"EditOptionsDisableLoup"

#define kPhatPadOptionsInkWidthNew          @"PhatPadOptionsInkWidthNew"
#define kTwitterOptionsUseLocation          @"TwitterOptionsUseLocation"
#define kTwitterAccountIdentifier           @"TwitterAccountIdentifier"
#define kTwitterOptionsDeleteText           @"TwitterOptionsDeleteText"
#define kTwitterShowTruncateWarning         @"TwitterShowTruncateWarning"
#define kTwitterOptionsPrompt               @"TwitterOptionsPrompt"
#define kTwitterShowUI                      @"TwitterShowUI"
#define kTwitterViewMode                    @"TwitterViewMode"
#define kPhatPadShowSizeDuringSelection     @"PhatPadShowSizeDuringSelection"
